# Generated by Django 3.2.8 on 2022-09-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=20, verbose_name='Familyasi')),
                ('middlename', models.CharField(max_length=20, verbose_name='Otasini ismi')),
                ('pinfl', models.CharField(max_length=16, unique=True, verbose_name='PINFL raqami')),
                ('passport', models.CharField(max_length=9, unique=True, validators=[reader.models.validate_passport], verbose_name='passport raqami')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=25, verbose_name='Email pochtasi')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.faculty', verbose_name='Fakulteti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
