# Generated by Django 3.2.8 on 2022-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fakultet nomi')),
                ('desc', models.TextField(blank=True, verbose_name='Fakultet xaqida')),
                ('image', models.ImageField(blank=True, upload_to='faculty_photo', verbose_name='Fakultet rasmi')),
            ],
        ),
    ]
