# Generated by Django 4.0.5 on 2022-10-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_student_faculty'),
        ('main', '0002_category_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('email', models.EmailField(blank=True, max_length=55)),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('showed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.student')),
            ],
        ),
    ]
